repos:
  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade
        language: python
        types: [ python ]
        args: [ "--py310-plus" ]

      - id: black
        name: black
        entry: black
        language: python
        require_serial: true
        types_or: [ python, pyi ]

      - id: isort
        name: isort
        entry: isort
        require_serial: true
        language: python
        types_or: [ cython, pyi, python ]
        args: [ "--filter-files" ]

      - id: name-tests-test
        name: python tests naming
        entry: name-tests-test
        language: python
        files: (^|/)tests/.+\.py$
        args: ["--pytest-test-first"]

      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        require_serial: true

      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types_or: [python, pyi]
        require_serial: true

      - id: vulture
        name: vulture
        language: python
        entry: vulture
        types: [python]
        require_serial: true

      - id: bandit
        name: bandit
        entry: bandit
        language: python
        types: [python]
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
